/**
 * ASELOVERS — Etsy Product Loader
 * Loads from products.json (generated by sync.js / server.js)
 * Caches in localStorage for 1 hour.
 */

const ETSY = (() => {
  const CACHE_KEY = 'ase_products_cache';
  const CACHE_TTL = 60 * 60 * 1000; // 1 hour
  let _products = [];
  let _callbacks = [];

  async function load(forceRefresh = false) {
    if (!forceRefresh) {
      const cached = getCache();
      if (cached) { _products = cached; notify(); return _products; }
    }
    try {
      const res = await fetch('products.json?t=' + Date.now());
      if (!res.ok) throw new Error('products.json not found');
      const data = await res.json();
      _products = (data.products || []).filter(p => p.isActive !== false);
      setCache(_products);
      notify();
    } catch (e) {
      console.warn('[ETSY] products.json yüklenemedi, örnek ürünler kullanılıyor');
      _products = getFallback();
      notify();
    }
    return _products;
  }

  function getAll() { return _products; }

  function getFiltered(cat) {
    if (!cat || cat === 'all') return _products;
    return _products.filter(p => p.category === cat);
  }

  function onLoad(fn) { _callbacks.push(fn); if (_products.length) fn(_products); }

  function notify() { _callbacks.forEach(fn => fn(_products)); }

  function getCache() {
    try {
      const raw = localStorage.getItem(CACHE_KEY);
      if (!raw) return null;
      const { ts, data } = JSON.parse(raw);
      if (Date.now() - ts > CACHE_TTL) return null;
      return data;
    } catch { return null; }
  }

  function setCache(data) {
    try { localStorage.setItem(CACHE_KEY, JSON.stringify({ ts: Date.now(), data })); } catch {}
  }

  function clearCache() { localStorage.removeItem(CACHE_KEY); }

  function getFallback() {
    return [
      { id: 'f1', title_tr: 'Örgü Tavşan Bebek', title_en: 'Personalized Crochet Bunny', description_tr: 'Kişiselleştirilmiş el yapımı tavşan.', description_en: 'Custom name handmade bunny.', price: 1912, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/0a28d4/8107536487/il_600x600.8107536487_c15v.jpg', url: 'https://aselovers.etsy.com', category: 'amigurumi', isNew: true, isActive: true },
      { id: 'f2', title_tr: 'Örgü Flamingo', title_en: 'Crochet Flamingo Plush', description_tr: 'Pembe bebek odası süsü.', description_en: 'Pink nursery decor.', price: 2287, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/d6d3ba/8097215171/il_600x600.8097215171_94ly.jpg', url: 'https://aselovers.etsy.com', category: 'amigurumi', isNew: false, isActive: true },
      { id: 'f3', title_tr: 'Perde Tutucu', title_en: 'Crochet Curtain Tiebacks', description_tr: 'Sevimli bebek odası perde tutucu.', description_en: 'Cute nursery curtain tieback.', price: 1874, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/552bb7/8136427496/il_600x600.8136427496_s7oy.jpg', url: 'https://aselovers.etsy.com', category: 'decor', isNew: false, isActive: true },
      { id: 'f4', title_tr: 'Saç Tokası Seti', title_en: 'Crochet Hair Clips Set', description_tr: 'El yapımı çocuk saç aksesuarları.', description_en: 'Handmade toddler hair accessories.', price: 411, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/b7c3b9/8111229068/il_600x600.8111229068_jycs.jpg', url: 'https://aselovers.etsy.com', category: 'accessory', isNew: true, isActive: true },
      { id: 'f5', title_tr: 'Örgü Ördek Oyuncak', title_en: 'Personalized Crochet Duck', description_tr: 'Organik pamuklu ördek amigurumi.', description_en: 'Organic cotton duck amigurumi.', price: 1650, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/8be45d/7988910978/il_600x600.7988910978_kexd.jpg', url: 'https://aselovers.etsy.com', category: 'amigurumi', isNew: false, isActive: true },
      { id: 'f6', title_tr: 'Tulumlu Örgü Ayı', title_en: 'Crochet Teddy Bear in Overalls', description_tr: 'El yapımı peluş ayı oyuncak.', description_en: 'Handmade plush teddy bear.', price: 1912, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/e5d94b/8082226247/il_600x600.8082226247_n28o.jpg', url: 'https://aselovers.etsy.com', category: 'amigurumi', isNew: true, isActive: true },
      { id: 'f7', title_tr: 'Örgü Omuz Çantası', title_en: 'Crochet Shoulder Bag', description_tr: 'El yapımı boho omuz çantası.', description_en: 'Handmade boho paper yarn bag.', price: 2028, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/1e70d7/8104701978/il_600x600.8104701978_jm5x.jpg', url: 'https://aselovers.etsy.com', category: 'bag', isNew: false, isActive: true },
      { id: 'f8', title_tr: 'Örgü Zürafa', title_en: 'Crochet Giraffe Plush', description_tr: 'Safari temalı zürafa amigurumi.', description_en: 'Safari themed giraffe amigurumi.', price: 1983, currency: 'TRY', image: 'https://i.etsystatic.com/65409401/r/il/0f0c1e/8025738321/il_600x600.8025738321_r4ep.jpg', url: 'https://aselovers.etsy.com', category: 'amigurumi', isNew: false, isActive: true },
    ];
  }

  /* ── Render helpers ── */
  function renderGrid(containerId, products, lang = 'tr') {
    const el = document.getElementById(containerId);
    if (!el) return;
    if (!products || products.length === 0) {
      el.innerHTML = `<div style="grid-column:1/-1;text-align:center;padding:60px 20px;color:var(--ink-s)"><div style="font-size:2.5rem;margin-bottom:12px">🧶</div><p>${I18N.get('products_empty')}</p><a href="https://aselovers.etsy.com" target="_blank" style="margin-top:16px;display:inline-block" class="btn btn-gold">${I18N.get('view_etsy')}</a></div>`;
      return;
    }
    el.innerHTML = products.map(p => productCard(p, lang)).join('');
    observeFadeUp();
  }

  function productCard(p, lang = 'tr') {
    const name = lang === 'tr' ? (p.title_tr || p.title_en) : (p.title_en || p.title_tr);
    const desc = lang === 'tr' ? (p.description_tr || p.description_en) : (p.description_en || p.description_tr);
    const catLabel = I18N.get('cat_' + p.category) || p.category;
    const badge = p.isNew ? `<span class="product-badge badge-new">New</span>` : '';
    const imgHtml = p.image
      ? `<img src="${p.image}" alt="${name}" loading="lazy" />`
      : `<div class="product-img-placeholder">🧶</div>`;
    const price = formatPrice(p.price, p.currency);

    return `<div class="product-card fade-up" onclick="window.open('${p.url}','_blank')">
      <div class="product-img-wrap">
        ${imgHtml}
        ${badge}
      </div>
      <div class="product-body">
        <div class="product-cat">${catLabel}</div>
        <div class="product-name">${name}</div>
        <div class="product-desc">${(desc || '').substring(0, 90)}${desc && desc.length > 90 ? '…' : ''}</div>
        <div class="product-footer">
          <div class="product-price">${price}</div>
          <a href="${p.url}" target="_blank" class="product-etsy-btn" onclick="event.stopPropagation()">Etsy ↗</a>
        </div>
      </div>
    </div>`;
  }

  return { load, getAll, getFiltered, onLoad, clearCache, renderGrid, productCard };
})();
